-- 应用发布表：App(Android/iOS) / EXE(Windows) 推送更新
-- 依据《云盘 App 推送更新方案（定稿）》§5.1 实现
CREATE TABLE app_release (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform        VARCHAR(16)  NOT NULL,                 -- android / ios / windows
    version_code    INT          NOT NULL,                 -- 递增构建号，同平台唯一
    version_name    VARCHAR(32)  NOT NULL,                 -- 展示版本，如 1.3.0
    apk_url         VARCHAR(512) NOT NULL,                 -- 下载地址(nginx /downloads/)
    file_size       BIGINT       NOT NULL DEFAULT 0,       -- 包体字节
    file_hash       VARCHAR(128) NOT NULL,                 -- 安装包 SHA-256 小写 hex
    update_notes    TEXT,                                  -- 更新说明(多行)
    force_update    BOOLEAN      NOT NULL DEFAULT FALSE,   -- 是否强制
    min_force_code  INT          NOT NULL DEFAULT 0,       -- 全局最低强制版本(可选)，0=不用
    rollout_percent INT          NOT NULL DEFAULT 100,     -- 灰度 0~100，100=全量
    status          VARCHAR(16)  NOT NULL DEFAULT 'draft', -- draft/published/disabled
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    published_at    TIMESTAMP,
    CONSTRAINT uk_app_release_platform_version UNIQUE (platform, version_code)
);

CREATE INDEX idx_app_release_platform_status
    ON app_release (platform, status, version_code DESC);